### ISSUE TITLE
Still being maintained?

### ISSUE THREAD

**Issue by dandanthedev** [creekdrops/svelte-pocketbase#3]
Hi, is this package still being maintained?

**Comment by CRYPTO-GENIK** [comment]
![image](https://github.com/creekdrops/svelte-pocketbase/assets/70092290/e801af64-43b5-4477-8370-d0389ccb5c57)

**Comment by creekdrops** [comment]
Unfortunately, I've been been busy with work and family life and have not had the time to commit to development on this project. I do hope to circle back around to this eventually, but I am open to PR's from anyone willing to contribute. Cheers!
